<table width="100%" cellpadding="2" cellspacing="2" border="0">


            <?php if($this->search_flag == false || empty($this->search_flag)){    ?>

            <tr>

              <td colspan="10"><?php 	echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?></td>

            </tr>

               <tr>

              <td align="left" height="35" colspan="10">&nbsp;

				<input type="submit" name="cmdSubmit" id="cmdSubmit" value="Add Select Answer To Response Set">

				&nbsp;&nbsp;&nbsp;

				<input type="button" name="cmdCancel" id="cmdCancel" value="Back To Response Set - Answer Listing">

              </td>

            </tr>

            <?php }    ?>

     
      <tr>

        <td class="tablesyle"><?php

	if( !empty($this->paginator) ){					?>

          <table width="100%" cellpadding="2" cellspacing="2" border="0" class='data'>

            <thead>

              <tr class="grdheader">

                <td width="3%" align="center"><input type="checkbox" name="chkAll" id="chkAll" value="1" style="border:0px"></td>

                <td align="left" width="37%">&nbsp;Answer Text</td>

                <td width="10%" align="center">Type</td>

                <td width="30%" align="center">Free Text</td>

                <td width="10%" align="center">Weighting</td>

                <td width="10%" align="center">Status</td>

              </tr>

            </thead>

            

            <tbody>

            

              <?php	foreach($this->paginator as $v){	?>

              

              <tr id="tdata">

                <td height="30" align="center"><input type="checkbox" name="answer_id[]" id="chk" value="<?php echo $v["answer_id"]; ?>-<?php echo $v["free_text"]; ?>" style="border:0px"></td>

               <td align="left">&nbsp;<b><a href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/answer/edit/aid/<?php	echo $v['answer_id']; ?>/page/<?php echo $this->pg; ?>/rset/1"><?php	echo stripslashes($v['answer_text']);	?></a></b></td>

                <td align="center"><?php echo ($v["answer_type"] == 'v')?'Verbatim':'Non Verbatim'; ?></td>

                <td align="left">&nbsp;<?php echo ($v['free_text'] == 'y')?stripslashes($v['free_text_caption']):'--'; ?></td>

                <td align="center"><?php echo $v['weightage']; ?></td>

                <td align="center"><?php echo $v["status"]; ?></td>

              </tr>

              <?php	}			?>

            </tbody>

          </table>

          <table width="100%" cellpadding="0" cellspacing="0" border="0">

            <tr>

              <td align="left" height="35" colspan="10">&nbsp;

				<input type="submit" name="cmdSubmit" id="cmdSubmit" value="Add Select Answer To Response Set">

				&nbsp;&nbsp;&nbsp;

				<input type="button" name="cmdCancel" id="cmdCancel" value="Back To Response Set - Answer Listing">

              </td>

            </tr>

            <?php if($this->search_flag == false || empty($this->search_flag)){    ?>

            <tr>

              <td colspan="10"><?php 	echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?></td>

            </tr>

            <?php }    ?>

          </table>

          <?php

	}else{											?>

          <table width="100%" cellpadding="2" cellspacing="2" border="0">

            <tr bgcolor="White">

              <td height="50" valign="middle" align="center">No answers found</td>

            </tr>

          </table>

          <?php

	}												?></td>

      </tr>

    </table>