<div class="pagetitle">
<table width="100%" cellpadding="2" cellspacing="2" border="0">
<tr>
	<td align="left" width="50%"><h2><?php echo $this->pgTitle; ?></h2></td>
	<td align="right" width="50%">
     <a class="menulinks" href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/responseset/add/"><b>Add New</b></a>
	 &nbsp;||&nbsp;
     <a class="menulinks" href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/responseset/index/"><b>View All</b></a>&nbsp;
    </td>
</tr>
</table>
</div>