<?php 

//echo  $gid = ( int ) $this->_getParam ( 'gid' ); 
 
    

?>



<div class="pagetitle">
<table width="100%" cellpadding="2" cellspacing="2" border="0">
<tr>
	<td align="left" width="50%"><h2><?php echo $this->pgTitle; ?></h2></td>
	<td align="right" width="50%">
	<?php  if($this->gid == 1){ ?>
	   <a class="menulinks" href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/user/add/gid/1/"><b>Add New</b></a>
	   &nbsp;||&nbsp;
	<?php } ?>
        <a class="menulinks" href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/user/index/gid/<?php echo $this->gid; ?>"><b>View All</b></a>&nbsp;
    </td>
</tr>
</table>
</div>