<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery/jquery.hint.js"></script>
<link type="text/css" href="<?php echo $this->baseUrl(); ?>/style/black-tie/jquery-ui-1.8.22.custom.css" rel="stylesheet" />
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery/jquery-ui-1.8.22.custom.min.js"></script>
<script type="text/javascript">
	$(function(){
		$('input[title!=""]').hint();
		// Tabs
		$('#tabs').tabs();
		//hover states on the static widgets
		$('#dialog_link, ul#icons li').hover(
			function() { $(this).addClass('ui-state-hover'); },
			function() { $(this).removeClass('ui-state-hover'); }
		);

	});
</script>
<header>
    <div id="logo"></div>
</header>
<div id="contentarea">
    <div id="tabs">
      <ul>
        <li><a href="#tabs-1"><b>Recover Password</b></a></li>
      </ul>
      <div id="tabs-1">
		<form id="mform"  action="recover-password.html" method="POST">
        <div id="frmclass">
        <fieldset>
<?php     if( !empty($this->errorMsg)){   ?>
            	<div class="error_msg">
            	    <?php echo $this->errorMsg; ?>
            	</div>
            <?php  }    ?>
        
        	<ul class="signup">
            	<li>
			
			<!-- <dl>
                    <dt><label>Username:</label></dt>
                    <dd><input type="text" name="txtUserName" id="txtUserName" value="" size="20" maxlength="20" class="username"></dd>
                 </dl>
                    <div align="center">OR</div>
                  -->
                 <dl>
                    <dt><label>E-mail :</label></dt>
                    <dd><input type="text" name="txtEmail" id="txtEmail" value="" size="50" maxlength="200"  title="Email address" class="email"></dd>
                    
					<dt><label>User Type :</label></dt>
                    <dd><select name="user_type" id="user_type" >
                    		<option	 value="1">-  Select -</option>
            				<option	 value="2">Member</option>
           					<option	 value="3">Client</option>
           				</select>
					</dd>
				</dl>
                </li>
            </ul>
            
            <div align="center" >
              <input type="submit" name="cmdSubmit" id="cmdSubmit" value="Submit">
              &nbsp;
              <input type="submit" name="cmdCancel" id="cmdCancel" value="Cancel">
            </div>
            </fieldset>
            </div>
        </form>
      </div>
    </div>
  </div>
  <!-- #content -->