<?php
    header("Content-Type: text/xml");
    
    echo '<?xml version="1.0" encoding="UTF-8"?>';

    echo '<app_setting>';
        echo '<success_flag>' . $this->success_flag . '</success_flag>';
    
    if (! empty($this->expired_flag)){
        echo '<session_expired>' . $this->expired_flag . '</session_expired>';
        echo '<msg>' . $this->msg . '</msg>';
    } else{
        echo '<report_flag>' . $this->report_flag . '</report_flag>';
        echo '<category_flag>' . $this->category_flag . '</category_flag>';
        echo '<max_count>' . $this->max_count . '</max_count>';
    }
    
    echo '</app_setting>';
?>