<?php
header ( "Content-Type: text/xml" );

echo '<?xml version="1.0" encoding="UTF-8"?>';
echo '<member_profile>';
if (empty ( $this->memberinfo )) {
	echo '<success_flag>0</success_flag>';
	echo '<msg>Member profile not found</msg>';
} else {
	echo '<success_flag>1</success_flag>';
	
	echo '<member_id>' . $this->memberinfo ['user_id'] . '</member_id>';
	echo '<firstname>' . $this->memberinfo ['firstname'] . '</firstname>';
	echo '<lastname>' . $this->memberinfo ['lastname'] . '</lastname>';
	echo '<email>' . $this->memberinfo ['email'] . '</email>';
	echo '<username>' . $this->memberinfo ['username'] . '</username>';
	echo '<signupdate>' . $this->memberinfo ['created_date'] . '</signupdate>';
	echo '<lastlogin_datetime>' . $this->memberinfo ['lastlogin_datetime'] . '</lastlogin_datetime>';
	echo '<group_id>' . $this->memberinfo ['group_id'] . '</group_id>';
	
	if (! empty ( $this->userInfo )) {
		
		echo '<device_id>' . $this->userInfo ['device_id'] . '</device_id>';
		echo '<country>' . $this->userInfo ['country_id'] . '</country>';
		echo '<dob>' . $this->userInfo ['dob'] . '</dob>';
		
		
		echo '<data_share>' . $this->userInfo ['data_share'] . '</data_share>';
	
	}
	echo '<interests>';
	if (! empty ( $this->interesteList )) {
		
		$exp = explode ( ',', $this->userInfo ['interest'] );
		foreach ( $this->interesteList as $k => $v ) {
			$selected_flag = false;
			foreach ( $exp as $jd ) {
				if ($jd == $v ['name']) {
					$selected_flag = true;
					break;
				}
			}
			if($selected_flag == true){
				echo '<interest>';
					echo '<id>' . $v ['intrest_id'] . '</id>';
					echo '<caption>' . $v ['name'] . '</caption>';
				echo '</interest>';
				
			}
		}
	
	}
echo '</interests>'; 
}
echo '</member_profile>';
?>