<script type="text/javascript">
$(document).ready(
	function() {
		$("table tr#tdata").mouseout(
				function () {
					$(this).removeClass('active_row');
					$(this).addClass('nonactive_row');
				}
			);
			$('table.data tbody tr:odd').addClass('odd');
			$('table.data tbody tr:even').addClass('even');
			$("table tr#tdata").mouseover(
				function () {
					$(this).removeClass('nonactive_row');
					$(this).addClass('active_row');
				}
			);
			  $(".paginationControl").change(
				    	function() {
				        	var page_index = null;
				        	page_index = $(this).val();
				        	window.location = page_index;
				    	}
				    );
		    $("#chkAll").click(
		    	function() {
		    		var checked_status = this.checked;
					$("input[@id=chk][type='checkbox']").each(
						function(){
							this.checked = checked_status;
						}
					);
		    	}
		    );
			$("#cmdDelete").click(
				function() {
					var cnt = 0;
					$("input[@id=chk][type='checkbox']").each(
						function(){
							if( this.checked == true){
								cnt++;
							}
						}
					);
					if(cnt > 0){
						ans = confirm("Confirm Operation on Selected Records(s) ?");
						if(ans == false){
							return false;
						}
					}else{
						alert('No Records Selected.');
						return false;
					}
				}
			);
	$('#txtAnsText').keyup(
		function(){
			$.ajax({	url: '<?php echo $this->baseUrl(); ?>/<?php echo $this->modulename; ?>/question/searchanswer/qid/<?php echo $this->qid; ?>/search_text/' + $(this).val(),
				success: function(data) {
					$('#answers_block').html(data);
				}	});
		}
	);
	}
)
</script>
<form name='frmAnswer' id='frmAnswer' method="POST" action="<?php echo $this->baseUrl(). "/" . $this->modulename; ?>/question/<?php echo strtolower($this->action); ?>answer">
<input type="hidden" name="qid" id="qid" value="<?php echo $this->qid; ?>">
<input type="hidden" name="pg" id="pg" value="<?php echo $this->pg; ?>">
<table width="100%" cellpadding="2" cellspacing="2" border="0">
<tr>
	<td class="searchdiv">
		<table width="100%" cellpadding="2" cellspacing="2" border="0">
		<tr>
            <td width="10%" align="left" height="30">&nbsp;<b>Question :</b></td>
            <td align="left" height="30">&nbsp;<?php echo stripslashes($this->queinfo['description']); ?></td>
		</tr>
		<tr>
            <td width="10%" align="left" height="30">&nbsp;<b>Answer Text :</b></td>
            <td align="left" height="30">&nbsp;<input type='text' name='txtAnsText' id='txtAnsText' value='' size="50" maxlength="50"></td>
		</tr>
		</table>
	</td>
</tr>
<tr><td height="3"></td></tr>
</table>
<!--  -->
<div id='answers_block'>
<?php echo $this->answers_block; ?>
</div>
<!--  -->
</form>