<script type="text/javascript">
$(document).ready(function(){
	$("table tr#tdata").mouseout(
		function () {
			$(this).removeClass('active_row');
			$(this).addClass('nonactive_row');
		}
	);

	$('table.data tbody tr:odd').addClass('odd');
	$('table.data tbody tr:even').addClass('even');

	$("table tr#tdata").mouseover(
		function () {
			$(this).removeClass('nonactive_row');
			$(this).addClass('active_row');
		}
	);

   $(".paginationControl").change(
		    	function() {
		        	var page_index = null;
		        	page_index = $(this).val();
		        	window.location = page_index;
		    	}
		    );

    $("#chkAll").click(
    	function() {
    		var checked_status = this.checked;
			$("input[@id=chk][type='checkbox']").each(
				function(){
					this.checked = checked_status;
				}
			);
    	}
    );

    $("#cmdAddResSet").click(
    		function() {
    			var cnt = 0;
    			$("input[@id=chk][type='checkbox']").each(
    				function(){
    					if( this.checked == true){
    						cnt++;
    					}
    				}
    			);
    			if(cnt > 0){
    				ans = confirm("Confirm Operation on Selected Records(s) ?");
    				if(ans == false){
    					return false;
    				}
    			}else{
    				alert('No Records Selected.');
    				return false;
    			}
    		}
    	);

    $('.cmdBack').click(
			function(){
				location.href = '<?php echo $this->baseUrl(). "/" . $this->modulename; ?>/question/responseset/qid/<?php echo $this->queinfo['question_id']; ?>/page/1';
			}
		);
});
</script>

<form name='frmAddQueResponseSet' id='frmAddQueResponseSet' method="POST" action="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/question/addresponseset">
<input type='hidden' name='qid' value='<?php echo $this->queinfo['question_id']; ?>'>
  <div class="contentdetails">
    <table width="100%" cellpadding="2" cellspacing="2" border="0">
      <tr>
        <td class="searchdiv">
			<table width="100%" cellpadding="2" cellspacing="2" border="0">
            <tr>
              <td width="10%" align="left" height="30">&nbsp;<b>Question :</b></td>
              <td width="90%" align="left" height="30">&nbsp;<?php echo stripslashes($this->queinfo['description']); ?></td>
            </tr>
          	</table>
        </td>
      </tr>
      <tr>
        <td height="3"></td>
      </tr>
      <tr>
        <td class="tablesyle"><?php
	if( !empty($this->paginator) ){					?>
	   <table width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
              <td colspan="10"><?php 	echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?></td>
            </tr>
               <tr>
              <td align="left" height="35" colspan="10">&nbsp;
                <input type="submit" name="cmdAddResSet" id="cmdAddResSet" value="Add Selected Response Set To Question">
                &nbsp;&nbsp;
                <input type="button" name="cmdBack" class="cmdBack" value="Back To Question Response Set Listing">
              </td>
            </tr>
          </table>
          <table width="100%" cellpadding="2" cellspacing="2" border="0" class='data'>
            <thead>
              <tr class="grdheader">
                <td width="3%" align="left"><input type="checkbox" name="chkAll" id="chkAll" value="1" style="border:0px"></td>
                <td align="left" width="97%">&nbsp;Title</td>
              </tr>
            </thead>
            <tbody>
              <?php	foreach($this->paginator as $v){	?>
              <tr id="tdata">
                <td align="left"><input type="checkbox" name="chk[]" id="chk" value="<?php echo $v["rs_id"]; ?>" style="border:0px"></td>
                <td align="left" height="30">&nbsp;<?php echo $v['title']; ?></td>
              </tr>
              <?php	}											?>
            </tbody>
          </table>
          <table width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
              <td align="left" height="35" colspan="10">&nbsp;
                <input type="submit" name="cmdAddResSet" id="cmdAddResSet" value="Add Selected Response Set To Question">
                &nbsp;&nbsp;
                <input type="button" name="cmdBack" class="cmdBack" value="Back To Question Response Set Listing">
              </td>
            </tr>
            <tr>
              <td colspan="10"><?php 	echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?></td>
            </tr>
          </table>
          <?php
	}else{											?>
          <table width="100%" cellpadding="2" cellspacing="2" border="0">
            <tr>
              <td height="50" valign="middle" align="center">No response set found for addition<br/><br/><br/>
					<a href='javascript:history.go(-1);'>Back To Question Response Set Listing</a>
              </td>
            </tr>
          </table>
          <?php
	}												?></td>
      </tr>
    </table>
  </div>
</form>