<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv='X-UA-Compatible' content='IE=8'>
<title>Edit Answer Details</title>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery/jquery-1.4.4.min.js"></script>
<script type="text/javascript">
$(document).ready(
	function() {
		$('.cmdClose').click(
			function(){
				 parent.$.fancybox.close();
			}
		);

<?php if( empty($this->id) ){   ?>
		$('#r1-<?php echo $this->aid; ?>', window.parent.document).html('&nbsp;&nbsp;&nbsp;<?php echo $this->answerinfo[1]; ?>');
		$('#r2-<?php echo $this->aid; ?>', window.parent.document).html('<?php echo $this->answerinfo[2]; ?>');
		$('#r3-<?php echo $this->aid; ?>', window.parent.document).html('<?php echo $this->answerinfo[3]; ?>');
		$('#r4-<?php echo $this->aid; ?>', window.parent.document).html('<?php echo $this->answerinfo[4]; ?>');
		$('#r5-<?php echo $this->aid; ?>', window.parent.document).html('<?php echo $this->answerinfo[5]; ?>');
		parent.$.fancybox.close();
<?php }    ?>

   });
</script>
<style type="text/css"">
html,body { font-size:0.850em; color:#333; font-family:Arial, verdana, Helvetica, sans-serif; margin:0; padding:0; }
input[type="submit"], input[type="button"] { padding:2px 5px; background-color:#cacaca; font-weight: bold; }
input[type="text"]{ border:1px solid #a2a2a2; padding: 1px; height:18px; }
textarea { padding: 1px; text-align:left; resize:none; }
h1,h2,h3{ font-family:Georgia, 'Times New Roman', Times, serif; text-shadow:0 1px 1px #d8d9d9; margin:3px; color: #666; border-bottom:3px double #999;
background:#efefef; padding:5px; }
ul {list-style:none; padding:5px; border:0px solid #FF0000; overflow:auto;}
li.label{ list-style:none; width:23%; font-weight:bold; border:0px solid #FF0000; float:left; padding:5px 0;}
li.inputbox { list-style:none; width:67%; border:0px solid #000; float:left; padding:3px 0;}
</style>
</head>
<body>
<form method="post" action='<?php echo $this->baseUrl(). "/" . $this->modulename; ?>/question/editans' >
  <input type='hidden' name='id' value='<?php echo $this->id; ?>'>
  <h2> Edit Answers </h2>
  <ul>
    <li class="label">Type :</li>
    <li class="inputbox">
      <select class="select" name="answer_type" id="answer_type">
        <option <?php echo (strtolower($this->answerinfo[2]) == 'nv')?'Selected':''; ?> value="nv">Non Verbatim</option>
        <option <?php echo (strtolower($this->answerinfo[2]) == 'v')?'Selected':''; ?> value="v">Verbatim</option>
      </select>
    </li>
    <li class="label">Text :</li>
    <li class="inputbox">
      <textarea rows="3" cols="50" name="answer_text" id="answer_text"><?php echo stripslashes($this->answerinfo[1]); ?></textarea>
      &nbsp;&nbsp;<font class="compulsory" >*</font> </li>
    <li class="label">Weighting :</li>
    <li class="inputbox">
      <input type="text" name="weightage" id="weightage" value="<?php echo $this->answerinfo[3]; ?>" size="5" maxlength="5">
    </li>
    <li class="label">Include Free Text Answer : </li>
    <li class="inputbox">
      <select class="select" name="free_text" id="free_text">
        <option <?php echo (strtolower($this->answerinfo[4]) == 'n')?'Selected':''; ?> value="n">No</option>
        <option <?php echo (strtolower($this->answerinfo[4]) == 'y')?'Selected':''; ?> value="y">Yes</option>
      </select>
    </li>
    <li class="label">Free Text Caption : </li>
    <li class="inputbox">
      <input type="text" name="free_text_caption" id="free_text_caption" value="<?php echo stripslashes($this->answerinfo[5]); ?>" size="50" maxlength="200">
    </li>
  </ul>
  <div align="center">
    <input type='submit' value='Update' name='cmdSubmit' id='cmdSubmit' />
    &nbsp;&nbsp;&nbsp;&nbsp;
    <input type='button' value='Cancel' name='cmdClose' id='cmdClose' class='cmdClose' />
  </div>
</form>
</body>
</html>