<script type="text/javascript">
$(document).ready(function(){
	$("table tr#tdata").mouseout(
		function () {
			$(this).removeClass('active_row');
			$(this).addClass('nonactive_row');
		}
	);

	$('table.data tbody tr:odd').addClass('odd');
	$('table.data tbody tr:even').addClass('even');

	$("table tr#tdata").mouseover(
		function () {
			$(this).removeClass('nonactive_row');
			$(this).addClass('active_row');
		}
	);
	   $(".paginationControl").change(
		    	function() {
		        	var page_index = null;
		        	page_index = $(this).val();
		        	window.location = page_index;
		    	}
		    );

    $("#chkAll").click(
    	function() {
    		var checked_status = this.checked;
			$("input[@id=chk][type='checkbox']").each(
				function(){
					this.checked = checked_status;
				}
			);
    	}
    );

	$(".cmdDelete").click(
		function() {
			var cnt = 0;
			$("input[@id=chk][type='checkbox']").each(
				function(){
					if( this.checked == true){
						cnt++;
					}
				}
			);
			if(cnt > 0){
				ans = confirm("Confirm Operation on Selected Records(s) ?");
				if(ans == false){
					return false;
				}
			}else{
				alert('No Records Selected.');
				return false;
			}
		}
	);
});
</script>
<form name='frmQuestion' id='frmQuestion' method="POST" action="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/question/index">
<div class="contentdetails">
<table width="100%" cellpadding="2" cellspacing="2" border="0">
<tr>
	<td class="searchdiv">
		<table width="100%" cellpadding="2" cellspacing="2" border="0">
		<tr>
			<td height="35" align="left" width="25%">&nbsp;Search By : <select class="select" name="cmbKey">
					<option value="description">&nbsp;Description&nbsp;</option>
				</select>
			</td>
			<td width="35%">
				<input type="text" value="" name="txtValue" id="txtValue" size="35" maxlength="50">
				&nbsp;&nbsp;&nbsp;&nbsp;
				<input type="submit" name="cmdSubmit" id="cmdSubmit" value="Search">
			</td>
			<td align="center">
<?php		if( $this->result_type == true){		?>
				<a href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/question/index/clear/results"><b>Clear Search Result</b></a>
<?php		}			?>
			</td>
		</tr>
		</table>
	</td>
</tr>
<tr><td height="3"></td></tr>

<tr>
	<td class="tablesyle">
<?php
	if( !empty($this->paginator) ){					?>
	 <table width="100%" cellpadding="0" cellspacing="0" border="0">
			<tr>
				<td colspan="10"><?php 	echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?></td>
			</tr>
			<tr>
				<td align="left" height="35" colspan="10">&nbsp;<input type="submit" name="cmdDelete" class="cmdDelete" value="Delete Selected Question"></td>
			</tr>
		</table>
		<table width="100%" cellpadding="2" cellspacing="2" border="0" class="data">
			<thead>
              <tr class="grdheader-large">
				<td height="30" width="3%" align="center"><input type="checkbox" name="chkAll" id="chkAll" value="1" style="border:0px"></td>
				<td height="30" align="left" width="65%">&nbsp;<b><font color="#ffffff">Question Description</font></b></td>
				<td height="30" width="15%" align="center"><b><font color="#ffffff">Answer Selection</font></b></td>
				<td height="30" width="10%" align="center"><b><font color="#ffffff">Answers</font></b></td>
				<td height="30" width="7%" align="center"><b><font color="#ffffff">Status</font></b></td>
			</tr>
			</thead>
			<tbody>
<?php	foreach($this->paginator as $v){	?>
			<tr bgcolor="White" id="tdata">
				<td height="30" align="center"><input type="checkbox" name="chk[]" id="chk" value="<?php echo $v['qinfo']["question_id"]; ?>" style="border:0px">
				<td align="left" height="30"><a href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/question/edit/id/<?php	echo $v['qinfo']['question_id']; ?>/page/<?php echo $this->pg; ?>"><?php	echo stripslashes(nl2br($v['qinfo']['description']));	?></a></td>
				<td height="30" align="center"><?php if($v['qinfo']["answer_type"] == 's'){ echo 'Single'; }else if($v['qinfo']["answer_type"] == 'm'){ echo 'Multiple'; }else{ echo 'Rating'; } ?></td>
				<td height="30" align="center"><a href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/question/<?php echo $v['controller']; ?>/qid/<?php	echo $v['qinfo']['question_id']; ?>/page/<?php echo $this->pg; ?>"><b>View</b></a></td>
				<td height="30" align="center"><?php echo $v['qinfo']["status"]; ?></td>
			</tr>
<?php	}											?>
			</tbody>
          </table>
          <table width="100%" cellpadding="0" cellspacing="0" border="0">
			<tr>
				<td align="left" height="35" colspan="10">&nbsp;<input type="submit" name="cmdDelete" class="cmdDelete" value="Delete Selected Question"></td>
			</tr>
			<tr>
				<td colspan="10"><?php 	echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?></td>
			</tr>
		</table>
<?php
	}else{											?>
		<table width="100%" cellpadding="2" cellspacing="2" border="0">
		<tr bgcolor="White">
			<td height="50" valign="middle" align="center">No Question Found</td>
		</tr>
		</table>
<?php
	}												?>
	</td>
</tr>
</table>
</div>
</form>