<div id="contentarea">
    <?php echo $this->leftmenu; ?>
    <div id="right-content">
      <div class="pgheader">
        <h2>Settings</h2>
      </div>
      <div class="area">
      	<ul class="icons">
      		<li><a href="<?php echo $this->baseUrl(); ?>/invite-friends.html"> <img src="<?php echo $this->baseUrl(); ?>/images/invite-friends.png" /> <br/>
      		Invite Friends </a></li>
      		<li><a href="<?php echo $this->baseUrl(); ?>/categories-of-interest.html"> <img src="<?php echo $this->baseUrl(); ?>/images/category.png" /> <br/>
      		Categories of Interest </a></li>
      		<!--
      		<li><a href="<?php echo $this->baseUrl(); ?>/invite-friends-to-mcubed.html"> <img src="<?php echo $this->baseUrl(); ?>/images/mcubed.png" /> <br/>
      		Join mCubed </a></li>
      		--><li>
      			<a href="#"><img src="<?php echo $this->baseUrl(); ?>/images/facebook.png" /> <br/>Share on Facebook </a>
      			<!--
                <?php if( empty($this->fb_login_flag) ){ ?>
      			   <a href="<?php echo $this->baseUrl(); ?>/share-on-facebook.html"><img src="<?php echo $this->baseUrl(); ?>/images/facebook.png" /> <br/>Share on Facebook </a>
      			<?php }else{ ?>
      			   <a href="<?php echo $this->baseUrl(); ?>/facebook-logout.html"><img src="<?php echo $this->baseUrl(); ?>/images/facebook.png" /> <br/>Logout</a>
      			<?php } ?>   -->
      		</li>
      		<li><!--
      		 <a href="<?php echo $this->baseUrl(); ?>/share-on-twitter.html"> <img src="<?php echo $this->baseUrl(); ?>/images/twitter.png" /> <br/>
      		 Share on Twitter </a>	 -->
      		 <a href="#"> <img src="<?php echo $this->baseUrl(); ?>/images/twitter.png" /> <br/> Share on Twitter </a>
      		 </li>
      		<li><a href="<?php echo $this->baseUrl(); ?>/notifications.html"> <img src="<?php echo $this->baseUrl(); ?>/images/notification.png" /> <br/>
      		Notifications </a></li>
      		 
      	</ul>
      </div>
    </div>
  </div>
  <!-- #content -->