<div class="pagetitle">
<table width="100%" cellpadding="2" cellspacing="2" border="0">
<tr>
	<td align="left" width="50%"><h2><?php echo $this->pgTitle; ?></h2></td>
	<td align="right" width="50%">
     <a class="menulinks" href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/survey/addquestions/id/<?php echo $this->sid; ?>/cid/<?php echo $this->cid; ?>"><b>Add question to survey</b></a>
	 &nbsp;||&nbsp;
     <a class="menulinks" href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/survey/questions/id/<?php echo $this->sid; ?>"><b>View all survey questions</b></a>&nbsp;
    </td>
</tr>
</table>
</div>