<?php
	header("Content-Type: text/xml");

	echo '<?xml version="1.0" encoding="UTF-8"?>';
	echo '<interest_list>';
	 echo "<success_flag>".$this->success_flag."</success_flag>";
	if(!empty($this->interest)){
	 
        foreach($this->interest as $v){
        	echo '<interest>';
               
               echo '<intrest_id>'.$v['intrest_id'].'</intrest_id>';
               echo '<name>'.$v['name'].'</name>';
                
                echo '</interest>';
      
        }
        
	}  
	echo '</interest_list>';
?>