<?php
	header("Content-Type: text/xml");
	echo '<?xml version="1.0" encoding="UTF-8"?>';
	
		
	if(!empty($this->expired_flag)){
		
		 echo '<session_expired>'.$this->expired_flag.'</session_expired>';
		
		
	} else {
	
	echo '<member_survey_list' . $this->answered_flag . '>';
	echo '<success_flag>'.$this->success_flag.'</success_flag>';
    if( !empty($this->survey) ) {
     //   foreach($this->survey as $k => $v){
     
        	
                echo '<survey>';               
                echo '<sid>'.$this->survey['survey_id'].'</sid>';
                echo '<title>'.str_replace('&','&amp;',$this->survey['title']).'</title>';

                echo '</survey>'; 
 
        // print_r($this->survey);
         
      //  }
    }else{
        echo '<msg>'.$this->msg.'</msg>';
    }
	echo '</member_survey_list' . $this->answered_flag . '>';
	
	}
?>