<div class="footer">
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
<tr>
	<td align="left" colspan="2">&nbsp;&nbsp;<b>You Said It : &copy; 2012. All Rights Reserved</b></td>
	<td align="right" colspan="2">Site designed &amp; developed by <a title="Compubits" target="_blank" href="http://www.compubits.com/"><b><font color="Black">Compubits</font></b></a>&nbsp;&nbsp;</td>
</tr>
</table>
</div>