<table width="100%" cellpadding="2" cellspacing="2" border="0">
  <tr>
    <td width="30%" height="100px"><img src="<?php echo $this->baseUrl(); ?>/images/ysi-logo-small.png" /></td>
    <td align="right" height="100px" width="70%" style="vertical-align: middle;"> Welcome <b><?php echo $this->admin_name; ?></b>&nbsp;&nbsp;(&nbsp;<a title="Logout" href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/login/logout"><b>Logout</b></a>&nbsp;) <br/>
      <br/>
      Last Login On <b><?php echo $this->lastlogin; ?></b></td>
  </tr>
  <tr>
    <td align="left" colspan="2">
    <table width="100%" border="0" align="center" cellpadding="0" cellspacing="2">
        <tr>
			<td height="30" class="mainmenucontrols">
				&nbsp;
				<a href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/">Home</a>
				&nbsp;<b>|</b>&nbsp;
				<a href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/user/index/gid/2">Member</a>
				&nbsp;<b>|</b>&nbsp;
				<a href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/user/index/gid/3">Client</a>
				&nbsp;<b>|</b>&nbsp;
				<a href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/categories/index">Categories</a>
				&nbsp;<b>|</b>&nbsp;
				<a href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/topic/index">Topics</a>
				&nbsp;<b>|</b>&nbsp;
				<a href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/survey/index">Survey</a>
				&nbsp;<b>|</b>&nbsp;
				<a href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/question/index">Question</a>
				&nbsp;<b>|</b>&nbsp;
				<a href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/answer/index">Answer</a>
				&nbsp;<b>|</b>&nbsp;
				<a href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/responseset/index">Response Sets</a>
				&nbsp;<b>|</b>&nbsp;
				<a href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/userinterest/index">User Interest</a>
				&nbsp;<b>|</b>&nbsp;
				<a href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/user/index/gid/1">Administrators</a>
				&nbsp;<b>|</b>&nbsp;
				<a href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/mailtemplates/index">Mail Templates</a>
	       		&nbsp;<b>|</b>&nbsp;
				<a href="<?php echo $this->baseUrl() . "/" . $this->modulename; ?>/config/index">Configuration</a>
			</td>
		</tr>
		</table>
	</td>
</tr>
</table>