<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
<tr>
	<td colspan="2" align="left">&nbsp;&nbsp;<b><?php echo date('l'); ?>, <?php echo date('jS F Y H:i'); ?></b></td>
	<td align="right" colspan="2">Site designed &amp; developed by <a title="Compubits" target="_blank" href="http://www.compubits.com/"><b><font color="White">Compubits</font></b></a>&nbsp;&nbsp;</td>
</tr>
</table>
