<form name='frmAdminLogin' method="POST" id='frmAdminLogin' action="<?php echo $this->baseUrl(); ?>/admin/login/process">
<div align="center">
	<img src="<?php echo $this->baseUrl(); ?>/images/ysi-logo.png" />
</div>
<div class="ad-login">
<h2 align="center">Backend Admin Module</h2>
	<ul>
		<li><label>User Name :</label></li>
		<li><input type="text" value="" name="txtUserName" id="txtUserName" /></li>
		<li><label>Password :</label></li>
		<li><input type="password" name="txtPassword" id="txtPassword" value="" /></li>
		<li class="smt-button"><input type="submit" name="cmdSubmit" value="Login"></li>
	</ul>
</div>
</form>