<script type="text/javascript">
$(document).ready(function() {

	  $('#frmCreateTopic').submit(
			function(){
				$('#cmdMSubmit').attr('disabled', 'disabled');
			}
		);
	
	  $('#cid').change(function(){
			var myLength = $("#name").val().length;
			var select = $('#cid').val().length;
			//console.log(myLength);
		//	console.log(select);
			if(myLength > 0  && select > 0){
				$("#cmdMSubmit").removeAttr("disabled");
			}else{
				$('#cmdMSubmit').attr('disabled', 'disabled');
			}
		});
	  $("#name").keyup(function(){
			var myLength = $("#name").val().length;
			var select = $('#cid').val().length;
			console.log(myLength);
		//	console.log(select);
			if(myLength > 0  && select > 0){
				$("#cmdMSubmit").removeAttr("disabled");
			}else{
				$('#cmdMSubmit').attr('disabled', 'disabled');
			}
		  });
});
</script>

<div id="contentarea">
    <?php echo $this->leftmenu; ?>
    <div id="right-content">
      <div class="pgheader">
        <h2>Create Post</h2>
      </div>
      <div class="area">
            <?php if( !empty($this->errorMsg)){   ?>
            	<div class="error_msg">
            	    <?php echo $this->errorMsg; ?>
            	</div>
            <?php  }    ?>
			<form id="frmCreateTopic" method="POST" action="create-topic.html">
            <ul>
              <li>Title : <font color="#FF0000">*</font> </li>
              <li><input type="text" class="largebox" name="name" id="name" value="<?php echo   !empty($this->post['name']) ? $this->post['name'] : '';?>" size="50" maxlength="250" ></li>
              
			<li>&nbsp;</li>
            
            <li>Category : <font color="#FF0000">*</font></li>
            <li>

             <select  id="cid"  name="cid" style="width: 250px;"  >
             <option   value="" > Select your Topic Category</option>
         <?php	foreach($this->catInfo as $k => $v){	?>
          			<option <?php echo ($this->post['cid'] == $v['categories_id'])? 'selected':''; ?>  value="<?php echo $v["categories_id"]; ?>" >  <?php echo $v["categories_name"]; ?></option>
         <?php	}	?>
         		</select>
         		
         		</li>
             
            </ul>
            <br/>
            <div>
              <input type="submit" disabled="disabled" name="cmdMSubmit" id="cmdMSubmit" value="Create Topic">
            </div>
      		</form>
      </div>
    </div>
  </div>
  <!-- #content -->